@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzMwNTYxNDh9.4frhKo_0gGB3-wT-0noW3FtBtwxgdpNpi_bsa8mvISg

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "mia",
  "email": "mia@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "mia@test.com",
  "password": "password"
}

######################## Items Routes #####################
### Index
GET http://localhost:3000/items.json

### Show
GET http://localhost:3000/items/2.json

### Create
POST http://localhost:3000/items.json
Content-Type: application/json

{
  "name": "test2",
  "description:": "test2 test2 test2",
  "img_url": "test2.png",
  "category_id": 1
}

### Update
PATCH http://localhost:3000/items/2.json
Content-Type: application/json

{
  "name": "test clothing",
  "description:": "test1 test2 test3",
  "img_url": "test3.png",
  "category_id": 1
}

### Destroy
DELETE http://localhost:3000/items/2.json


############## Outfit Items ##############
### Create
POST http://localhost:3000/outfit_items
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "outfit_id": 1,
  "item_id": 1
}